const actionTypes = {
    LOAD_STATUS: "LOAD_STATUS",
    SHOW_STATUS: "SHOW_STATUS",
    LOAD_LANDING_LIST: "LOAD_LANDING_LIST",
    LOAD_DETAIL_DELAY_GRAPH: "LOAD_DETAIL_DELAY_GRAPH",
    LOAD_PROFILE_WEBS: "LOAD_PROFILE_WEBS",
    ADD_PROFILE_WEB: "ADD_PROFILE_WEB",
    DELETE_PROFILE_WEBS: "DELETE_PROFILE_WEBS",
    GOOGLE_OAUTH2: "GOOGLE_OAUTH2"
}

export default actionTypes